// <auto-generated />
using Emlak.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emlak.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316145938_FixSyntaxMigration")]
    partial class FixSyntaxMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Emlak.API.Models.AboutInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeImages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsInBusiness")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AboutInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Modern Emlak olarak 20 yılı aşkın tecrübemizle hayalinizdeki evi bulmanıza yardımcı oluyoruz.",
                            OfficeImages = "https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80,https://images.unsplash.com/photo-1572025442646-866d16c84a54?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
                            YearsInBusiness = 20
                        });
                });

            modelBuilder.Entity("Emlak.API.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MapCoordinates")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomCount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingAge = 5,
                            ContactInfo = "Ahmet Yılmaz - 0555 123 45 67",
                            Description = "Şehrin merkezinde, ulaşım noktalarına yakın harika deniz manzaralı geniş daire.",
                            Floor = 4,
                            ImageUrls = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80,https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
                            MapCoordinates = "41.0082,28.9784",
                            Price = 3500000m,
                            Properties = "Kombi,Asansör,Kapalı Otopark,Balkon",
                            RoomCount = "3+1",
                            SquareMeters = 120,
                            Title = "Deniz Manzaralı Lüks Daire"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
